first commit with yaml file

diff --git a/.github/workflows/Test-Sample-ManageraApproval-ZIP.yml b/.github/workflows/Test-Sample-ManageraApproval-ZIP.yml
--- a/.github/workflows/Test-Sample-ManageraApproval-ZIP.yml
+++ b/.github/workflows/Test-Sample-ManageraApproval-ZIP.yml
@@ -113,15 +113,26 @@ jobs:
 
           DIST_DIR="dist/hms-app/browser"
 
+          if [ ! -d "$DIST_DIR" ]; then
+            echo "❌ Browser folder not found"
+            exit 1
+          fi
+
+          ZIP_PATH="$GITHUB_WORKSPACE/$ZIP_NAME"
+
           echo "Using dist folder: $DIST_DIR"
+          echo "Creating ZIP: $ZIP_PATH"
 
           cd "$DIST_DIR"
-          zip -r "../../$ZIP_NAME" .
+
+          zip -r "$ZIP_PATH" .
+
           cd -
 
           echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
           echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
-          ls -lh $ZIP_NAME
+
+          ls -lh "$ZIP_PATH"
 
       # ✅ Upload artifact
       - name: Upload artifact
